package com.neider.rutaescolar.personalruta.infraestructure.gui;

import com.neider.rutaescolar.personalruta.application.ActualizarAsistenteUseCase;
import com.neider.rutaescolar.personalruta.application.ActualizarBusUseCase;
import com.neider.rutaescolar.personalruta.application.ActualizarConductorUseCase;
import com.neider.rutaescolar.personalruta.application.BuscarAsistentePorIdUseCase;
import com.neider.rutaescolar.personalruta.application.BuscarBusPorIdUseCase;
import com.neider.rutaescolar.personalruta.application.BuscarConductorPorIdUseCase;
import com.neider.rutaescolar.personalruta.application.CrearAsistenteUseCase;
import com.neider.rutaescolar.personalruta.application.CrearBusUseCase;
import com.neider.rutaescolar.personalruta.application.CrearConductorUseCase;
import com.neider.rutaescolar.personalruta.application.EliminarAsistenteUseCase;
import com.neider.rutaescolar.personalruta.application.EliminarBusUseCase;
import com.neider.rutaescolar.personalruta.application.EliminarConductorUseCase;
import com.neider.rutaescolar.personalruta.application.ListarAsistentesUseCase;
import com.neider.rutaescolar.personalruta.application.ListarBusesUseCase;
import com.neider.rutaescolar.personalruta.application.ListarConductoresUseCase;
import com.neider.rutaescolar.personalruta.domain.ports.BusRepository;
import com.neider.rutaescolar.personalruta.infraestructure.db.DatabaseConfig;
import com.neider.rutaescolar.personalruta.infraestructure.db.MySqlBusRepository;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Asistente.EliminarYBuscarAsistente;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Bus.ActualizarBus;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Bus.CrearBus;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Bus.EliminarYBuscarBus;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Bus.ListarBuses;
import com.neider.rutaescolar.personalruta.domain.ports.AsistenteRepository;
import com.neider.rutaescolar.personalruta.domain.ports.ConductorRepository;
import com.neider.rutaescolar.personalruta.infraestructure.db.MySqlAsistenteRepository;
import com.neider.rutaescolar.personalruta.infraestructure.db.MySqlConductorRepository;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Asistente.CrearAsistente;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Asistente.ListarAsistente;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Conductor.ActualizarConductor;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Conductor.CrearConductor;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Conductor.EliminarYBuscarConductor;
import com.neider.rutaescolar.personalruta.infraestructure.gui.Conductor.ListarConductores;

import java.util.logging.Logger;
import javax.swing.JPanel;

public class VentanaPrincipal extends javax.swing.JFrame {

    private static final Logger logger
            = Logger.getLogger(VentanaPrincipal.class.getName());

    
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    private void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // TODO add your handling code here:

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        Bus = new javax.swing.JMenu();
        ActualizarBus = new javax.swing.JMenuItem();
        CrearBus = new javax.swing.JMenuItem();
        EliminarBus = new javax.swing.JMenuItem();
        ListarBuses = new javax.swing.JMenuItem();
        Asistente = new javax.swing.JMenu();
        ActualizarAsistente = new javax.swing.JMenuItem();
        CrearAsistente = new javax.swing.JMenuItem();
        EliminarYBuscarAsistente = new javax.swing.JMenuItem();
        ListarAsistentes = new javax.swing.JMenuItem();
        Conductor = new javax.swing.JMenu();
        ActualizarConductor = new javax.swing.JMenuItem();
        CrearConductor = new javax.swing.JMenuItem();
        EliminarConductor = new javax.swing.JMenuItem();
        ListarConductor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial");
        setBackground(new java.awt.Color(0, 102, 255));
        setForeground(java.awt.Color.gray);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        Bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenida.setText("BIENVENIDO A RUTA ESCOLAR");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/3d177a6607ab07c71eeae9a6bc3efdd7-diseno-de-autobus-escolar-amarillo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        MenuPrincipal.setBackground(new java.awt.Color(255, 255, 0));

        Bus.setText("Bus  ");

        ActualizarBus.setText("Actualizar Bus");
        ActualizarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBusActionPerformed(evt);
            }
        });
        Bus.add(ActualizarBus);

        CrearBus.setText("Crear Bus");
        CrearBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBusActionPerformed(evt);
            }
        });
        Bus.add(CrearBus);

        EliminarBus.setText("Eliminar y Buscar Bus");
        EliminarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBusActionPerformed(evt);
            }
        });
        Bus.add(EliminarBus);

        ListarBuses.setText("Listar Buses");
        ListarBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarBusesActionPerformed(evt);
            }
        });
        Bus.add(ListarBuses);

        MenuPrincipal.add(Bus);

        Asistente.setText("Asistente");

        ActualizarAsistente.setText("Actualizar Asistente");
        ActualizarAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarAsistenteActionPerformed(evt);
            }
        });
        Asistente.add(ActualizarAsistente);

        CrearAsistente.setText("Crear Asistente");
        CrearAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearAsistenteActionPerformed(evt);
            }
        });
        Asistente.add(CrearAsistente);

        EliminarYBuscarAsistente.setText("Buscar y Eliminar Asistente");
        EliminarYBuscarAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarYBuscarAsistenteActionPerformed(evt);
            }
        });
        Asistente.add(EliminarYBuscarAsistente);

        ListarAsistentes.setText("Listar Asistentes");
        ListarAsistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarAsistentesActionPerformed(evt);
            }
        });
        Asistente.add(ListarAsistentes);

        MenuPrincipal.add(Asistente);

        Conductor.setText("Conductor");

        ActualizarConductor.setText("Actualizar Conductor");
        ActualizarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarConductorActionPerformed(evt);
            }
        });
        Conductor.add(ActualizarConductor);

        CrearConductor.setText("Crear Conductor");
        CrearConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearConductorActionPerformed(evt);
            }
        });
        Conductor.add(CrearConductor);

        EliminarConductor.setText("Eliminar y Buscar Conductor");
        EliminarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarConductorActionPerformed(evt);
            }
        });
        Conductor.add(EliminarConductor);

        ListarConductor.setText("Listar Buses");
        ListarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarConductorActionPerformed(evt);
            }
        });
        Conductor.add(ListarConductor);

        MenuPrincipal.add(Conductor);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarAsistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarAsistenteActionPerformed

    private void CrearBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBusActionPerformed
  
        BusRepository busRepository = new MySqlBusRepository();

        CrearBusUseCase crearUC = new CrearBusUseCase(busRepository);

        CrearBus panel = new CrearBus(crearUC);

        mostrarPanel(panel);
    }//GEN-LAST:event_CrearBusActionPerformed

    private void ActualizarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBusActionPerformed

    BusRepository busRepository = new MySqlBusRepository();
    ActualizarBusUseCase useCase = new ActualizarBusUseCase(busRepository);

    ActualizarBus panel = new ActualizarBus(useCase);
    mostrarPanel(panel);
    }//GEN-LAST:event_ActualizarBusActionPerformed

    private void EliminarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBusActionPerformed
        BusRepository busRepository = new MySqlBusRepository();

        BuscarBusPorIdUseCase buscarUC = new BuscarBusPorIdUseCase(busRepository);
        EliminarBusUseCase eliminarUC = new EliminarBusUseCase(busRepository);
        ActualizarBusUseCase actualizarUC = new ActualizarBusUseCase(busRepository);

        EliminarYBuscarBus panel = new EliminarYBuscarBus(buscarUC, eliminarUC, actualizarUC);
        mostrarPanel(panel);
    }//GEN-LAST:event_EliminarBusActionPerformed

    private void ListarBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarBusesActionPerformed
        BusRepository busRepository = new MySqlBusRepository();

        ListarBusesUseCase listarUC = new ListarBusesUseCase(busRepository);
        BuscarBusPorIdUseCase buscarUC = new BuscarBusPorIdUseCase(busRepository);

        ListarBuses panel = new ListarBuses(listarUC, buscarUC);
        mostrarPanel(panel);
    }//GEN-LAST:event_ListarBusesActionPerformed

    private void CrearAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearAsistenteActionPerformed
        AsistenteRepository asistenteRepository = new MySqlAsistenteRepository();

        CrearAsistenteUseCase crearUC
                = new CrearAsistenteUseCase(asistenteRepository);

        CrearAsistente panel = new CrearAsistente(crearUC);

        mostrarPanel(panel);
    }//GEN-LAST:event_CrearAsistenteActionPerformed

    private void EliminarYBuscarAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarYBuscarAsistenteActionPerformed
        AsistenteRepository asistenteRepository = new MySqlAsistenteRepository();

       
        BuscarAsistentePorIdUseCase buscarUC
                = new BuscarAsistentePorIdUseCase(asistenteRepository);

        EliminarAsistenteUseCase eliminarUC
                = new EliminarAsistenteUseCase(asistenteRepository);

        ActualizarAsistenteUseCase actualizarUC
                = new ActualizarAsistenteUseCase(asistenteRepository);

                EliminarYBuscarAsistente panel
                = new EliminarYBuscarAsistente(buscarUC, eliminarUC, actualizarUC);

        mostrarPanel(panel);
    }//GEN-LAST:event_EliminarYBuscarAsistenteActionPerformed

    private void ListarAsistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarAsistentesActionPerformed
  AsistenteRepository asistenteRepository = new MySqlAsistenteRepository();

        ListarAsistentesUseCase listarUC
                = new ListarAsistentesUseCase(asistenteRepository);

        BuscarAsistentePorIdUseCase buscarUC
                = new BuscarAsistentePorIdUseCase(asistenteRepository);

        ListarAsistente panel
                = new ListarAsistente(listarUC, buscarUC);

        mostrarPanel(panel);
    }//GEN-LAST:event_ListarAsistentesActionPerformed

    private void ActualizarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarConductorActionPerformed

        ConductorRepository conductorRepository = new MySqlConductorRepository();
        ActualizarConductorUseCase useCase = new ActualizarConductorUseCase(conductorRepository);

        ActualizarConductor panel = new ActualizarConductor(useCase);
        mostrarPanel(panel);
    }//GEN-LAST:event_ActualizarConductorActionPerformed

    private void CrearConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearConductorActionPerformed
        ConductorRepository conductorRepository = new MySqlConductorRepository();
        CrearConductorUseCase crearUC = new CrearConductorUseCase(conductorRepository);

        CrearConductor panel = new CrearConductor(crearUC);
        mostrarPanel(panel);
    }//GEN-LAST:event_CrearConductorActionPerformed

    private void EliminarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarConductorActionPerformed
        ConductorRepository conductorRepository = new MySqlConductorRepository();

        BuscarConductorPorIdUseCase buscarUC
                = new BuscarConductorPorIdUseCase(conductorRepository);
        EliminarConductorUseCase eliminarUC
                = new EliminarConductorUseCase(conductorRepository);
        ActualizarConductorUseCase actualizarUC
                = new ActualizarConductorUseCase(conductorRepository);

        EliminarYBuscarConductor panel
                = new EliminarYBuscarConductor(buscarUC, eliminarUC, actualizarUC);

        mostrarPanel(panel);
    }//GEN-LAST:event_EliminarConductorActionPerformed

    private void ListarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarConductorActionPerformed
          ConductorRepository conductorRepository = new MySqlConductorRepository();

        ListarConductoresUseCase listarUC
                = new ListarConductoresUseCase(conductorRepository);

        BuscarConductorPorIdUseCase buscarUC
                = new BuscarConductorPorIdUseCase(conductorRepository);

        ListarConductores panel
                = new ListarConductores(listarUC, buscarUC);

        mostrarPanel(panel);
    }//GEN-LAST:event_ListarConductorActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        System.out.println("Entró al main de VentanaPrincipal");

        // Look & Feel Nimbus
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Crear y mostrar la ventana
        java.awt.EventQueue.invokeLater(() -> {
            System.out.println("Creando VentanaPrincipal...");
            new VentanaPrincipal().setVisible(true);
        });
    }




       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarAsistente;
    private javax.swing.JMenuItem ActualizarBus;
    private javax.swing.JMenuItem ActualizarConductor;
    private javax.swing.JMenu Asistente;
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JMenu Bus;
    private javax.swing.JMenu Conductor;
    private javax.swing.JMenuItem CrearAsistente;
    private javax.swing.JMenuItem CrearBus;
    private javax.swing.JMenuItem CrearConductor;
    private javax.swing.JMenuItem EliminarBus;
    private javax.swing.JMenuItem EliminarConductor;
    private javax.swing.JMenuItem EliminarYBuscarAsistente;
    private javax.swing.JMenuItem ListarAsistentes;
    private javax.swing.JMenuItem ListarBuses;
    private javax.swing.JMenuItem ListarConductor;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
