package com.neider.rutaescolar.personalruta.infrastructure.gui;

import com.neider.rutaescolar.personalruta.infrastructure.gui.Bus.ActualizarBus;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class RutaEscolar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(RutaEscolar.class.getName());

    public RutaEscolar() {
        initComponents();
        jPanel1.setLayout(new BorderLayout());
    }

    private void mostrarPanel(JPanel panel) {
        jPanel1.removeAll();
        jPanel1.add(panel, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // TODO add your handling code here:
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        Bus = new javax.swing.JMenu();
        ActualizarBus = new javax.swing.JMenuItem();
        CrearBus = new javax.swing.JMenuItem();
        EliminarBus = new javax.swing.JMenuItem();
        ListarBuses = new javax.swing.JMenuItem();
        Asistente = new javax.swing.JMenu();
        ActualizarAsistente = new javax.swing.JMenuItem();
        CrearAsistente = new javax.swing.JMenuItem();
        EliminarAsistente = new javax.swing.JMenuItem();
        ListarAsistentes = new javax.swing.JMenuItem();
        Conductor = new javax.swing.JMenu();
        ActualizarConductor = new javax.swing.JMenuItem();
        CrearConductor = new javax.swing.JMenuItem();
        EliminarConductor = new javax.swing.JMenuItem();
        ListarConductor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO A RUTA ESCOLAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 570, 120));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/neider/rutaescolar/personalruta/infrastructure/gui/icons/3d177a6607ab07c71eeae9a6bc3efdd7-diseno-de-autobus-escolar-amarillo.png"))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 520, 234));

        MenuPrincipal.setBackground(new java.awt.Color(255, 255, 0));

        Bus.setText("Bus  ");

        ActualizarBus.setText("Actualizar Bus");
        ActualizarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBusActionPerformed(evt);
            }
        });
        Bus.add(ActualizarBus);

        CrearBus.setText("Crear Bus");
        CrearBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBusActionPerformed(evt);
            }
        });
        Bus.add(CrearBus);

        EliminarBus.setText("Eliminar y Buscar Bus");
        Bus.add(EliminarBus);

        ListarBuses.setText("Listar Buses");
        Bus.add(ListarBuses);

        MenuPrincipal.add(Bus);

        Asistente.setText("Asistente");

        ActualizarAsistente.setText("Actualizar Asistente");
        ActualizarAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarAsistenteActionPerformed(evt);
            }
        });
        Asistente.add(ActualizarAsistente);

        CrearAsistente.setText("Crear Asistente");
        Asistente.add(CrearAsistente);

        EliminarAsistente.setText("Eliminar y Buscar Asistente");
        Asistente.add(EliminarAsistente);

        ListarAsistentes.setText("Listar Asistentes");
        Asistente.add(ListarAsistentes);

        MenuPrincipal.add(Asistente);

        Conductor.setText("Conductor");

        ActualizarConductor.setText("Actualizar Conductor");
        Conductor.add(ActualizarConductor);

        CrearConductor.setText("Crear Conductor");
        Conductor.add(CrearConductor);

        EliminarConductor.setText("Eliminar y Buscar Conductor");
        Conductor.add(EliminarConductor);

        ListarConductor.setText("Listar Buses");
        Conductor.add(ListarConductor);

        MenuPrincipal.add(Conductor);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarAsistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarAsistenteActionPerformed

    private void CrearBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearBusActionPerformed

    private void ActualizarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBusActionPerformed
        ActualizarBus panel = new ActualizarBus();
        mostrarPanel(panel);
    }//GEN-LAST:event_ActualizarBusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RutaEscolar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarAsistente;
    private javax.swing.JMenuItem ActualizarBus;
    private javax.swing.JMenuItem ActualizarConductor;
    private javax.swing.JMenu Asistente;
    private javax.swing.JMenu Bus;
    private javax.swing.JMenu Conductor;
    private javax.swing.JMenuItem CrearAsistente;
    private javax.swing.JMenuItem CrearBus;
    private javax.swing.JMenuItem CrearConductor;
    private javax.swing.JMenuItem EliminarAsistente;
    private javax.swing.JMenuItem EliminarBus;
    private javax.swing.JMenuItem EliminarConductor;
    private javax.swing.JMenuItem ListarAsistentes;
    private javax.swing.JMenuItem ListarBuses;
    private javax.swing.JMenuItem ListarConductor;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
