package com.neider.rutaescolar.personalruta.infraestructure.gui.Bus;

import com.neider.rutaescolar.personalruta.application.ActualizarBusUseCase;
import com.neider.rutaescolar.personalruta.domain.model.Bus;
import com.neider.rutaescolar.personalruta.domain.model.EstadoBus;
import com.neider.rutaescolar.personalruta.infraestructure.gui.VentanaPrincipal;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class ActualizarBus extends javax.swing.JPanel {

    private final ActualizarBusUseCase actualizarBusUseCase;
    private Bus busActual;

    public ActualizarBus(ActualizarBusUseCase actualizarBusUseCase) {
        this.actualizarBusUseCase = actualizarBusUseCase;
        initComponents();
        inicializarEstados();
        configurarEventos();
    }

    private void inicializarEstados() {
        Estados.removeAllItems();
        for (EstadoBus estado : EstadoBus.values()) {
            Estados.addItem(estado.name());
        }
    }

    public void cargarBus(Bus bus) {
        this.busActual = bus;
        if (bus == null) {
            limpiarCampos();
            return;
        }

        CampoPlaca.setText(bus.getPlaca());
        if (bus.getEstado() != null) {
            Estados.setSelectedItem(bus.getEstado().name());
        } else if (Estados.getItemCount() > 0) {
            Estados.setSelectedIndex(0);
        }
    }

    private void configurarEventos() {
        Guardar.addActionListener(e -> onGuardar());
        Limpiar.addActionListener(e -> limpiarCampos());
        Cancelar.addActionListener(e -> onCancelar());
    }

private void onGuardar() {
    if (busActual == null) {
        JOptionPane.showMessageDialog(
                this,
                "No hay bus cargado para actualizar. Selecciona uno desde la lista primero.",
                "Sin bus",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String nuevaPlaca = CampoPlaca.getText();
    String estadoStr = (String) Estados.getSelectedItem();

    try {
        busActual.actualizarPlaca(nuevaPlaca);

        if (estadoStr != null && !estadoStr.isBlank()) {
            EstadoBus nuevoEstado
                    = EstadoBus.valueOf(estadoStr.trim().toUpperCase());
            busActual.cambiarEstado(nuevoEstado);
        }

        Bus actualizado = actualizarBusUseCase.ejecutar(busActual);

        JOptionPane.showMessageDialog(
                this,
                "Bus actualizado:\n" + actualizado,
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Error de datos",
                JOptionPane.ERROR_MESSAGE
        );
    } catch (RuntimeException ex) {
        JOptionPane.showMessageDialog(
                this,
                "Error al actualizar el bus en la base de datos.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}



    private void limpiarCampos() {
        CampoPlaca.setText("");
        if (Estados.getItemCount() > 0) {
            Estados.setSelectedIndex(0);
        }
        CampoPlaca.requestFocus();
    }

    private void onCancelar() {
        limpiarCampos();

        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }

        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setLocationRelativeTo(null);
        vp.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Limpiar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        ActualizarBus = new javax.swing.JLabel();
        Placa = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        CampoPlaca = new javax.swing.JTextField();
        Estados = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N

        Limpiar.setText("LIMPIAR");

        Cancelar.setText("CANCELAR");

        ActualizarBus.setFont(new java.awt.Font("Segoe UI", 0, 33)); // NOI18N
        ActualizarBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActualizarBus.setText("Actualizar Bus");

        Placa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Placa.setText("PLACA:");
        Placa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Estado.setText("ESTADO:");
        Estado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO", "SUSPENDIDO" }));

        Guardar.setText("GUARDAR");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/note-edit-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Cancelar)
                        .addGap(94, 94, 94)
                        .addComponent(Guardar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CampoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(ActualizarBus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ActualizarBus)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarBus;
    private javax.swing.JTextField CampoPlaca;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Estado;
    private javax.swing.JComboBox<String> Estados;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Placa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

